### PR TITLE
Typo fix

### LINKED ISSUE #78: typo in Chunk API
net.canarymod.api.world.Chunk interface has a typo... `getMaxHeigth()` should be `getMaxHeight()`

### PR DESCRIPTION
**Pull request by lewiscowper**
Fixes #78

### CODE REVIEW

**Comment by Larry1123** [comment]
Please redo this with keeping the old method using @ Deprecated
The way you currently are doing it any plugin using the old method would no longer work.

**Comment by darkdiplomat** [comment]
We also ask that you read and sign our Contribitors License Agreement Form
https://dl.dropboxusercontent.com/u/25586491/Canary/CanaryModTeam_CLA.pdf

**Comment by lewiscowper** [comment]
According to the java docs on oracle, that should deprecate the appropriate functions. I've done your CLA, but it doesn't say where to send it other than just by email to the canarymodteam. Is the info@ address suitable?

**Comment by darkdiplomat** [comment]
oh, yes, either  info@canarymod.net or viadmin@visualillusionsent.net is fine

**Pull request merged**
