### PR TITLE
Clojure plugin base

### PR DESCRIPTION
**Pull request by DanThiffault**
I've added the required code so that clojure plugins can be developed. This includes the ability to update live using an nrepl. For an example please see https://github.com/DanThiffault/ClojureCanaryPlugin

### CODE REVIEW

**Comment by Larry1123** [comment]
Should this be open still?

**Comment by cpmcdaniel** [comment]
No. I had a conversation with Dan about the clojure plugin I started working on and he basically "handed me the keys". At this point, the plugin I've developed has more goodies and is "more readier" ;-)

**Comment by cpmcdaniel** [comment]
For reference: https://github.com/cpmcdaniel/CanaryClojureLibrary

**Comment by DanThiffault** [comment]
Agreed & I'm closing. Thank you @cpmcdaniel for taking the reigns.

**Pull request closed without merging**
