### PR TITLE
NativeTranslateBridge needs to be public (for other implementations)

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by darkdiplomat** [comment]
Negative
It's full intended use is to intergrate the Canary translator with the Minecrarft internal one

**Comment by jamierocks** [comment]
Neptune is implemented <b>VERY</b> differently, we do not follow the same package structure as CanaryMod.

**Comment by jamierocks** [comment]
Nor do we want to use the 'net.canarymod' package

**Comment by darkdiplomat** [comment]
I would give this a second consideration had it not been deleted and unable to reopen.

When you make requests, you need to provide detailed reasoning as to what was changed and why the change was made and reasoning as to why it should be accepted.

**Pull request closed without merging**
