### PR TITLE
Feature/slf4j

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by Larry1123** [comment]
Why Depreciate  Logman?

**Comment by jamierocks** [comment]
Because I assumed you would eventually remove it?

**Comment by toddharrison** [comment]
This might be useful. Currently I have some trouble writing unit tests when I've used logman in my classes.

**Comment by jamierocks** [comment]
Your unit tests are for canarymod right and not canarylib?

Sent from Outlook




On Thu, Jun 18, 2015 at 6:43 PM -0700, "Todd Harrison" <notifications@github.com> wrote:












This might be useful. Currently I have some trouble writing unit tests when I've used logman in my classes.

**Pull request closed without merging**
