### PR TITLE
WhitelistProvider is now an interface

### PR DESCRIPTION
**Pull request by jamierocks**
I left BackboneWhitelist, so you can decide on weather to keep it :)

### CODE REVIEW

**Comment by darkdiplomat** [comment]
I'm not following the logic in making this an Interface.
What implements it? Why is this an interface and not the others like ReserveList or Operators?

**Comment by jamierocks** [comment]
It is unable to be easily implementated on platforms such as Forge as it currently is

**Comment by Larry1123** [comment]
@jamierocks I don't get why ReserveList and Operators are not done the same here also.

**Comment by jamierocks** [comment]
I realized that after I made the pr. I will update later on.

**Comment by jamierocks** [comment]
Replaced by #129.

**Pull request closed without merging**
